### ISSUE TITLE
Re "Plotting API" notebook

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/unstructured-grid-viz-cookbook#7]
In the `notebooks/03-uxarray-vis/01-plot-api.ipynb`, even though it is clarified in a Note cell that this is only an introduction to the following notebooks in the same chapter, should we still avoid providing plots in the "Grid Plotting" and "UxDataset & UxDataArray Plotting" parts and stick only to providing function signatures or samples (without displayed plot)?

This is because this intro notebook looks a bit plots-heavy and the plots in those parts are just duplicates of what are existing in the following notebooks. 

The plots in the "Customization" part looks pretty though!

**Comment by philipc2** [comment]
> This is because this intro notebook looks a bit plots-heavy and the plots in those parts are just duplicates of what are existing in the following notebooks.

I've thought about this, and while there are some duplicate plots, the key difference is the `plot-api` notebook does not provide any context or further discussion into these plots. 

The plots here are also extremely bare-bones, with the only parameters passed into them being the title. 

I'll give it some thought and see if there's anything I can do to make it flow better.

**Comment by erogluorhan** [comment]
> > This is because this intro notebook looks a bit plots-heavy and the plots in those parts are just duplicates of what are existing in the following notebooks.
> 
> I've thought about this, and while there are some duplicate plots, the key difference is the `plot-api` notebook does not provide any context or further discussion into these plots.
> 
> The plots here are also extremely bare-bones, with the only parameters passed into them being the title.
> 
> I'll give it some thought and see if there's anything I can do to make it flow better.

Got it; fine with me!
