### ISSUE TITLE
Transfer ownership to ProjectPythia

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/unstructured-grid-viz-cookbook#8]
... to have this show up in [ProjectPythia](https://github.com/ProjectPythia)'s [cookbook gallery](https://cookbooks.projectpythia.org/)

**Comment by erogluorhan** [comment]
@philipc2 please let me know (preferably via Zulip) when you have no local dev on this repo, so I can do this. Afterwards, we can still keep working on the Pythia side, if there is anything remaining.

**Comment by philipc2** [comment]
> @philipc2 please let me know (preferably via Zulip) when you have no local dev on this repo, so I can do this. Afterwards, we can still keep working on the Pythia side, if there is anything remaining.

As of right now, I don't have any local dev, everything is up to date. 

Let's begin the transfer during/after our Raijin meeting tomorrow?
